### ISSUE TITLE
KubernetesFixture: we need this now

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1157]
I started working on the neonDESKTOP dashboard proxies and realized that I'd like to write the unit tests as I'm coding this.  I've created the **test-api** container image to support this.

The plan is to define a new `KubernetesFixture` class in the existing **Neon.Kube.Xunit** library and have this be able to connect to an existing cluster as well as be able to provision/de-provision a new temporary test cluster.  Here's are the basic requirements:

* Deploy a new cluster from a cluster definition:

  The cluster definition will need to reference user/machine specific properties, like the IP addresses to use for the cluster nodes as well as hosting information for cloud as well as remote Hypervisor environments including credentials.  Some of these will be secrets served by 1Password and other values can come from a file or environment variables on the user's machine.

* We'll eventually need the hosting managers to be able to de-provision their clusters.  We don't currently support this.

* It would be nice to be able to **reset** a cluster to a known initial state.  Ideally, this would:
  * Remove all services and pods from the **default** namespace and potentially other namespaces specified by the developer
  * Remove all PVs associated with the services removed above
  * Remove all ingress rules associated with the removed services as well 
  * Remove any new users, roles, etc.

I'm going to break this up into two phases so we won't block a first demo too much longer. 

---

**Phase 1:**

- [ ] Add `ISecretsProvider` to **Neon.Common** to define how secrets can be programmatically.
- [ ] Create a new **Neon.Deployment** library and relocate the `AwsCli` and `OnePassword` classes from neonCLOUD.  We'll still retain **Neon.Cloud.Deployment** for additional private code and definitions.
- [ ] Have the `OnePassword` class implement `ISecretsProvider` or create a new class that maps this.
- [ ] Modify `PreprocessReader` (**Neon.Common**) to be able handle secret values as well as environment variables.
- [ ] `KubernetesFixture` features:
    - [ ] Connect to current cluster: this will be easy and should be enough to implement the neonDESKTOP proxy tests

---

**Phase 2:**

- [ ] We need to figure out a way to make the master 1Password available automatically to `PreprocessReader`.  This will be easy for CI/CD machines because this will be available as an environment variable initialized by a GitHub Action.  The problem is how to do this for developers running unit tests in Visual Studio.

- [ ] `KubernetesFixture` features:
    - [ ] Provision new cluster
    - [ ] De-provision cluster
    - [ ] Specific cluster via specific cluster config (text)
    - [ ] Reset cluster
    - [ ] WSL2
    - [ ] [Kind](https://kind.sigs.k8s.io/) cluster support?
