### ISSUE TITLE
Reliable cluster shutdown and life cycle neon-cli commands

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1281]
neonKUBE needs a way to cleanly shutdown clusters.  This doesn't appear to be something that's really supported yet in Kubernetes.  Here are the issues we're seeing when shutting down a cluster (even just a single node one):

1. Kubernetes doesn't seem to have a built-in way to order how pods and services are shut down.  We're seeing problems where OpenEBS related services appear to be shutdown before dependent services like databases, etc. resulting in hangs and timeouts as well as the possibility of data loss when these dependent services aren't able to flush any cached data.

2. Solutions like [Graceful Node Shutdown](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/) look like they're intended for just for shutting down a single cluster node for maintenance or decommissioning while the rest of the cluster remains running.  This works by gracefully evicting pods from the target node, presumably to be rescheduled on the remaining nodes.  This is not what we're trying to achieve for cluster shutdown.

3. Master nodes will also be stopped during cluster shutdown which means that we'll want to take special care to ensure that the etcd servers are shutdown properly.

4. We need to make sure that a rebooted cluster ends up in approximately the same state as it was when it was shutdown.  In particular we need to ensure that services start back up with the same number of replicas and it would be nice if the scheduler restarted pods on the same nodes where they were running previously.  This means that we can't have the scheduler rescheduling pods and services during shutdown (another reason why number 2 above won't work).

5. For clusters deployed in cloud environments like Azure and AWS an important cluster shutdown use case will be to reduce costs by shutting down a cluster when it's not needed; for example, a test cluster that's required during working hours.  Shutting down the cluster VMs will save the hourly VM fees (but there will still fees for the disk storage).

   [Azure VMs](https://www.parkmycloud.com/does-azure-charge-for-stopped-vm/) can be in stopped or stopped/deallocated state where the latter is when VM billing pauses and [AWS VMs](https://www.parkmycloud.com/aws-stopped-instance-cost/) has a single stopped state where billing stops.  Note that just shutting down a VM from within the operating system won't put a VM into stopped state from either cloud's perspective; this has to happen via a cloud API.

6. My initial thought was to coordinate cluster shutdown from the client (neon-cli or neonDESKTOP) but as @marcusbooyah pointed out, this assumes that the client will remain running and connected for an operation that might take several minutes to complete.  A user shutting down a cluster and then immediately closing their laptop screen putting it to sleep would probably result in one or more of the VMs not actually stopping resulting in unhappy users seeing cloud fees they weren't expecting.  We **really don't want to see this happen**.

   Instead, let's embed the shutdown logic into the **neon-cluster-operator**

**TASKS:**

- [ ] Persist the cluster definition and cluster login as Kubernetes secrets during cluster setup

- [ ] Configure new pod PriorityClass values (defined in a new `PodPriority` class):
    - [ ] system-node-critical = 2000001000 (Kubernetes built-in)
    - [ ] system-cluster-critical = 2000000000 (Kubernetes built-in)
    - [ ] neon-storage = 1000006000
    - [ ] neon-data-tier = 1000005000
    - [ ] neon-api-tier = 1000004000
    - [ ] neon-app-tier = 1000003000
    - [ ] user-data-tier = 1000002000
    - [ ] user-api-tier = 1000001000
    - [ ] user-app-tier = 1000000000

- [ ] Update our service deployments to set **PriorityClass**

- [ ] Enable [Graceful Node Shutdown](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/) by setting: **ShutdownGracePeriod** and **ShutdownGracePeriodCriticalPods** in the **kubelet.service** file

- [ ] Modify **neon-cluster-operator:**
    - [ ] Configure loop timers as environment variables
    - [ ] Break loops out into separate virtual operators and define CRDs for each operator:
        - [ ] **neon-harborsync-operator**
        - [ ] **neon-shutdown-operator**
    - [ ] Run this on the masters as a daemon-set
    - [ ] Replace the KV settings with configs
    - [ ] We'll need to implement leader election to prevent multiple operator replicas from stomping on each other

- [ ] Implement the new `ClusterProxy` shutdown logic
    - [ ] This will be initiated by setting a `shutdownNow` property to TRUE in the **neon-shutdown-operator's** CRD
    - [ ] Stop the **kube-scheduler** static pod on all master nodes (by moving its manifest from `/etc/kubernetes/*` to `/etc/neon-boot/manifests.*`.
    - [ ] List all deployments
    - [ ] Group deployments by explicit or implicit PriorityClass and also make note of the current number of replicas for each deployment
    - [ ] Generate a custom bash scripts for each node that uses crictl to stop and remove all deployment pods on each nodes.  Each script will stop the pods for deployments with the same PriorityClass and will stop all pods with this class in parallel.
    - [ ] SSH into each node and run the scripts for each PriorityClass across the cluster
    - [ ] At this point, all that should remain running will be the core Kubernetes services.
    - [ ] Stop the **kube-api-server** static pods
    - [ ] Identify the master node running the **etcd leader**
    - [ ] Stop the non-leader **etcd** static pods
    - [ ] Stop the lead **etcd** static pod
    - [ ] Backup the etcd data?
    - [ ] Update the `/etc/neon-boot/restore` script with the commands that restore the static pod manifests on each of the master nodes.
    - [ ] SSH into all nodes and issue `shutdown --poweroff 0` commands to shutdown all nodes

- [ ] Implement the **neon-boot** systemd service that runs on all nodes: it executes and then deletes the `/etc/neon-boot/restore` script if present.  We'll deploy this on all nodes but we're only using it on master nodes for now.

- [x] Add cluster cluster life cycle commands to **neon-cli:**
    - [x] **cluster start**
    - [x] **cluster stop**
    - [x] **cluster remove**
    - [x] **cluster sleep**
    **JEFF UPDATE:** I'm going to track this separately here: #1445

**Comment by jefflill** [comment]
After nearly completing priority class assignments during cluster setup (only harbor related apps remain), it appears that clean cluster shutdown is already happening without messing static pods, etc.

Restart seems to work OK, but the process takes a while and is a little chaotic because the apps are not starting in any particular order and so there are a lot of pod terminations and restarts happening until things finally stabilize.  We'll track some ideas for mitigating this here: #1446

**Comment by jefflill** [comment]
I'm going to close this as we're tracking this is two new issues.

**Comment by jefflill** [comment]
Reopening this because we're seeing problems.  I tried shutting down a single node neon-desktop built-in cluster and watched the VM console terminate an apparently endless set of pods over maybe 20 minutes.  I think the problem may be that kublet is restarting pods for some reason; I don't know for sure.

We need to look at this again.

**Comment by jefflill** [comment]
I've temporarily disabled **Stop** commands for neon-cli and neon-desktop.

**Comment by jefflill** [comment]
**CLOSING:** this all has been through a couple refactor passes, so we're going to close this one.
