### ISSUE TITLE
Use new GitHub package REST APIs

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1300]
**WOOHOO!** It looks like GitHub has added new REST APIs for managing packages:

https://docs.github.com/en/rest/reference/packages

including:

* Listing packages by type and visibility
* Deleting a package by version!!!

Unfortunately, I don't see a way to change the package visibility but we could at least check for this during the node image build and fail the build if any referenced packages aren't public.

**TASKS:**

- [x] Remove the GitHub API hack from **neon-assistant** and re-code this in the **Neon.Deployment** library as actual REST calls.
- [x] Publish the new **neon-assistant**
- [x] We need to handle pagination for the new GitHub REST APIs
- [x] Add a check to node image builds that verifies that all referenced **setup images** are **actually public** before starting the image build.

**Comment by jefflill** [comment]
**DONE**
