### ISSUE TITLE
neon-cluster-operator refactor

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1302]
The current **neon-cluster-operator** is currenty very simplistic and it's time to refactor this to follow Kubernetes operator conventions:

* monitor custom resources for settings and cluster state changes
* control loops that transition resources from current to desired state
* operator simplicity: intended to do one thing well
* perform leader election where that makes sense

The current **neon-cluster-operator** is:

1.  launching the **neon-setup-grafana** and **neon-setup-harbor** jobs when these setup activities haven't completed.  We're going to relocate this logic to the actual setup code: #1301 

2. periodically verifying that Harbor has all of the node images, loading any missing ones from GHCR.

**THE PLAN:**

The basic plan is to replace the **neon-cluster-manager** with micro services handling specific activities.  I am thinking that we should consolidate multiple _virtual_ operators into **neon-cluster-manager** somewhat like [kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) does.

**THINGS TO THINK ABOUT:**

We need to study Kubernetes operator/controller best practices:

https://sdk.operatorframework.io/docs/best-practices/best-practices/ `<--- operator Ten Commandments`
https://kubernetes.io/docs/concepts/extend-kubernetes/operator/
https://kubernetes.io/docs/concepts/architecture/controller/

We also need to understand how much the .NET `KubernetesClient` can help us:

[KubeSharper: An SDK for Building Kubernetes Operators in C#](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj9reCivI70AhVnITQIHVP6C_MQFnoECCAQAQ&url=https%3A%2F%2Fprojekter.aau.dk%2Fprojekter%2Ffiles%2F334904545%2Fvorlov18_MasterThesis_KubeSharper.pdf&usg=AOvVaw0jz18F75C8RsAwvusrSHbY)  `<--- excellent reading`

_JEFF: This looks super interesting.  It even supports CRD generation, but I can't find any source or nugets._

Here are some possible alternatives:

* https://github.com/ContainerSolutions/dotnet-operator-sdk (very minimal)
* https://github.com/engineerd/kubecontroller-csharp/tree/master/KubeController (another incomplete weekend project)
* https://github.com/buehler/dotnet-operator-sdk (looks more promising, 22K+ [nuget KubeOps](https://www.nuget.org/packages/KubeOps/))

**WORK ITEMS:**

- [x] **Remove** the **Harbor** and **Grafana** setup related code as part of #1301.

- [x] Relocate Helm charts from **Neon.Kube** to **Neon.Kube.Setup** to avoid circular project references when the operator depends on **Neon.Kube** but also needs to generate its CRDs which will need to be added to the installed Helm charts.

- [x] Integrate the operator into the **Neon.Kube.Setup** build by copying its generated CRDs and other Helm chart related files from the project as a post-build event.

**Comment by jefflill** [comment]
FYI @marcusbooyah: **The `CreateDatabaseAsync()` method in the **neon-setup-grafana** service was a bit hard to follow:

1. The database connection is opened and closed a bunch of times which seems unnecessary.

2. You're not using the **Neon.Postgres** extensions which make it much easier to execute SQL commands as well as handling database creation.

The original method looked like this:
```
        private async Task CreateDatabaseAsync(string dbName, string dbUser, string dbPass = null)
        {
            try
            {
                await using var conn = new NpgsqlConnection(await GetConnectionStringAsync());
                await conn.OpenAsync();

                var dbInitialized = true;

                await using (var cmd = new NpgsqlCommand($"SELECT DATNAME FROM pg_catalog.pg_database WHERE DATNAME = '{dbName}'", conn))
                await using (var reader = await cmd.ExecuteReaderAsync())
                {
                    await reader.ReadAsync();
                    if (!reader.HasRows)
                    {
                        await conn.CloseAsync();
                        Log.LogInfo($"[{KubeNamespaces.NeonSystem}-db] Creating database '{dbName}'.");
                        dbInitialized = false;
                        await using (var createCmd = new NpgsqlCommand($"CREATE DATABASE {dbName}", conn))
                        {
                            await conn.OpenAsync();
                            await createCmd.ExecuteNonQueryAsync();
                            await conn.CloseAsync();
                        }
                    }
                }

                if (conn.State != System.Data.ConnectionState.Open)
                {
                    await conn.OpenAsync();
                }

                await using (var cmd = new NpgsqlCommand($"SELECT 'exists' FROM pg_roles WHERE rolname='{dbUser}'", conn))
                await using (var reader = await cmd.ExecuteReaderAsync())
                {
                    await reader.ReadAsync();
                    if (!reader.HasRows)
                    {
                        await conn.CloseAsync();
                        Log.LogInfo($"[{KubeNamespaces.NeonSystem}-db] Creating user '{dbUser}'.");
                        dbInitialized = false;

                        string createCmdString;
                        if (!string.IsNullOrEmpty(dbPass))
                        {
                            createCmdString = $"CREATE USER {dbUser} WITH PASSWORD '{dbPass}'";
                        }
                        else
                        {
                            createCmdString = $"CREATE ROLE {dbUser} WITH LOGIN";
                        }

                        await using (var createCmd = new NpgsqlCommand(createCmdString, conn))
                        {
                            await conn.OpenAsync();
                            await createCmd.ExecuteNonQueryAsync();
                            await conn.CloseAsync();
                        }
                    }
                }

                if (!dbInitialized)
                {
                    if (conn.State != System.Data.ConnectionState.Open)
                    {
                        await conn.OpenAsync();
                    }

                    Log.LogInfo($"[{KubeNamespaces.NeonSystem}-db] Setting permissions for user '{dbUser}' on database '{dbName}'.");
                    await using (var createCmd = new NpgsqlCommand($"GRANT ALL PRIVILEGES ON DATABASE {dbName} TO {dbUser}", conn))
                    {
                        await createCmd.ExecuteNonQueryAsync();
                        await conn.CloseAsync();
                    }
                }
            }
            catch (Exception e)
            {
                Log.LogError(e);

                throw e;
            }
```
I relocated this to `CreateSystemDatabaseAsync()` in **KubeSetup.Operations.cs** and simplified this to:
```
        private static async Task CreateSystemDatabaseAsync(ISetupController controller, Kubernetes k8s, string name, string username, string password = null)
        {
            Covenant.Requires<ArgumentNullException>(controller != null, nameof(k8s));
            Covenant.Requires<ArgumentNullException>(k8s != null, nameof(k8s));

            using (var connection = new NpgsqlConnection(await GetSystemDatabaseConnectionStringAsync(controller, k8s)))
            {
                await connection.OpenAsync();

                // Create the database if it doesn't already exist.

                using (var reader = await connection.ExecuteReaderAsync($"SELECT DATNAME FROM pg_catalog.pg_database WHERE DATNAME = '{name}'"))
                {
                    if (!reader.HasRows)
                    {
                        await connection.ExecuteNonQueryAsync($"CREATE DATABASE {name}");
                    }
                }

                // Create the user if it doesn't already exist.

                using (var reader = await connection.ExecuteReaderAsync($"SELECT 'exists' FROM pg_roles WHERE rolname='{username}'"))
                {
                    if (!reader.HasRows)
                    {
                        if (!string.IsNullOrEmpty(password))
                        {
                            await connection.ExecuteNonQueryAsync($"CREATE USER {username} WITH PASSWORD '{password}'");
                        }
                        else
                        {
                            await connection.ExecuteNonQueryAsync($"CREATE ROLE {username} WITH LOGIN");
                        }
                    }
                }

                // Grant the user full access to the database.

                await connection.ExecuteNonQueryAsync($"GRANT ALL PRIVILEGES ON DATABASE {name} TO {username}");
            }
        }
```
We should try to use our command extensions as much as possible since it'll be easy to have memory leaks and other problems when manually disposing commands, especially for ad-hoc commands like this.  Exceptions to this would be when we'd want to use prepared statements for performance.

**Comment by jefflill** [comment]
**NOTE:** I've temporarily disabled cluster operator installation during cluster setup.

**Comment by jefflill** [comment]
**DONE**
