### ISSUE TITLE
BREAKING: NeonService and Kubernetes liveness changes

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1304]
It looks like liveness probes for **NeonService** based services is configured incorrectly and we also need to tweak how NeonService based services report health:

![image](https://user-images.githubusercontent.com/4908431/141373386-bbd94adb-0419-4fe1-85e7-5d0d40af7381.png)

These probes are configured to use HTTPS but NeonService does not and will not support this because we don't want to require all services to bring in the ASP.NET stack.  We currently support writing a status file with values like: **not-started**, **starting**, **running**, **unhealthy**, or **terminated**.  The idea was that the container image would include a script that Docker would call for health probes that would examine this file and return the appropriate exit code.

**NOTE:** **NeonService** doesn't currently enable this managing this status file by default.

Kubernetes file based probes simply check for the existence of a file to determine that the container is healthy.

We're going to need to tweak both NeonService as well as our Helm charts to get this to work.  It would be nice if we could also support Docker health probes out-of-the-box as well.  We may need to differentiate between running on Windows or Linux (OS/X).

### TODOs:

- [x] **Linux:**
    - [x] **BREAKING:** Instead of passing the path to the status file to the **NeonService** constructor, let's change this to a status folder path.  This is a breaking change but frankly, I don't believe anybody is actually using this feature yet.
     - [x] The default status folder path will be `/`
     - [x] Passing a special **DISABLED** status folder disables the feature
     - [x] **NeonService** will update the `/health-status` file as the service health changes (just as it does already)
     - [x] **NeonService** will also create the `/health-check` script file when the service is health or otherwise delete the file.  Kubernetes liveness probes should be configured execute this script which will indicate that the service is not ready for non-zero exit codes.  This may also be referenced by Dockerfile **HEALTHCHECK** statements.

- [x] **Windows and OS/X:** Let's **disable this entire feature** on these platforms since we're mostly trying to support Docker and Kubernetes here.

**Comment by jefflill** [comment]
I've modified **NeonService** to behave as described above.  This means that the service health status file will now be at **/health-status** and the health check script will be at **/health-check** by default.

**Comment by jefflill** [comment]
**DONE**
