### ISSUE TITLE
neon-desktop tasks

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1462]
neon-desktop needs some TLC before the next demo:

- [x] cluster-setup:
    - [x] Wizard is creating a cStor disk for neon-desktop; we shouldn't be doing this.  This is due to a recent neonKUBE change where we configure OpenEBS on at least one node and we must be defaulting to cStor instead of Jiva?
    - [x] Handle partially configured clusters
    - [x] Cancel button missing in first wizard step
    - [x] Allow wizard to be minimized?
    - [x] Wizard z-level shouldn't be always on top
    - [x] First step during cluster setup is highlighted as running even after the step finishes
    - [x] Reconcile actual cluster state with `Desktop/settings.yaml`
        - [x] Hyper-V
        - [x] XenServer
    - [x] Wizard needs to verify available disk and RAM.
    - [x] Alert the user when setup fails
    - [x] Include node image download in elapsed time
    - [x] Hide **Next** button when operation is in progress.  Also switch the **Next/Cancel** button positions.
    - [x] Verify that **cancel** works
        - [x] download
        - [x] prepare
        - [x] setup
        - [x] cancel provisioning not working
        - [x] cancel node image download
        - [x] cancel VHDX decompress
        - [x] remove VHDX
        - [x] remove VM
        - [x] remove internal switch and NAT
        - [x] Display cancel pending message
        - [x] Remove partially deployed clusters
    - [x] Confirm setup cancel with a dialog
    - [x] Failure when internal Hyper-V NAT already exists?
- [x] Installers:
    - [x] Uninstall:
        - [x] Kill neon-desktop process if running: [link](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/taskkill)
        - [x] `neon-install-helper.exe` tool is not hidden during uninstall
- [x] neon-cli lifecycle commands:
    - [x] cluster start
    - [x] cluster stop
    - [x] cluster remove
    - [x] cluster pause
    - [x] cluster reset
- [x] Beautify (as dark-mode?) : going to track separately this here #1473 
- [x] Taskbar status icon
    - [x] Black when disconnected
    - [x] Blink green during setup
    - [x] Ping the current cluster (if any) with a small request periodically to update the task bar icon
    - [x] Blink yellow/green when unhealthy
    - [x] Blink red/black when partially configured or broken
    - [x] Steady power button when off
    - [x] Blinking power button when sleeping
    - [x] Hide icon until app is fully initialized
- [x] Add menus/commands:
    - [x] Current cluster menu
        - [x] No clusters listed when only neon-desktop cluster present
        - [x] Ensure that selecting clusters works
    - [x] Create built-in cluster (disable when one already exists)
    - [x] Start cluster
        - [x] disable when not supported by hosting manager
        - [x] disable when already running
    - [x] Stop cluster
        - [x] disable when not supported by hosting manager
        - [x] disable when stopped or paused
    - [x] Pause cluster
        - [x] disable when not supported by hosting manager
        - [x] disable when already stopped or paused
    - [x] Resume cluster
       - [x] disable when not supported by hosting manager
       - [x] disable when running or stopped
    - [x] Delete cluster
        - [x] disable when not supported by hosting manager
        - [x] **AreYouSureDialog**
    - [x] Deploy cluster:
        - [x] Prompt to create built-in cluster when none exists and not disabled
        - [x] Create arbitrary cluster via cluster definition
    - [x] Logout
    - [x] Reset cluster to factory defaults: this is wired up but needs to be implemented #1480
    - [x] Relocate **Deploy Cluster** to after separator (with the other static commands)
- [x] Toast:
    - [x] After cluster setup completion, cancellation or failure
    - [x] Before/after:
        - [x] Cluster stop
        - [x] Cluster explicit resume
        - [x] Cluster automatic resume
        - [x] Cluster pause
        - [x] Cluster delete
- [x] Dashboard is blank
- [x] Dashboard popup menu is wonky on Chrome/Edge
- [x] Window sizing issues on high-res laptop: [info](https://blogs.windows.com/windowsdeveloper/2017/05/19/improving-high-dpi-experience-gdi-based-desktop-apps/)
- [x] Better unhandled exception handling
- [x] Don't fail on launch when running as admin when the desktop service isn't running (easier for development and debugging)
- [x] App doesn't exit when not running as admin and the desktop service isn't running.  The app reports the problem via an alert but keeps going.
- [x] Built-in cluster:
    - [x] Increase cluster disk size from 32GiB --> 40GiB
    - [x] neonKUBE change default storage to Jiva
- [x] Settings
    - [x] Built-in cluster lifecycle behavior:
        - [x] Run only when signed into Windows and app is running
        - [x] Mode to continue running when signed out
    - [x] Docker credentials (add to built-in cluster): tracking here #1479
    - [x] Toast configuration
    - [x] Settings dialog
- [x] About dialog
- [x] Check for updates: tracking here #1479
- [x] Query new configmap resource for cluster status: **neon-status/cluster-status**
- [x] Cluster Wizards: limit height of **steps panel** and automatically scroll to keep current step visible:
    - [x] Built-in cluster wizard
    - [x] Custom cluster wizard
- [x] Built-in cluster life-cycle
    - [x] start when app launches
    - [x] stop when app exits

**Comment by jefflill** [comment]
**DONE!** The neon-desktop app is looking pretty good now; good enough for demos.

We'll be tracking bugs and addition issues here:

#1479
