### ISSUE TITLE
Release endgame

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#238]
Here's the Dockercon June 12, 2018 release endgame:

- [ ] Coding: completed by 6/4/2018
    - [x] ClusterFixture DNS features
    - [ ] Local registry (#153)
        - [x] neon_docker_registry module
        - [x] deploy stoke prod and core clusters
    - [x] Consul transient test errors (and #232)
    - [x] Couchbase fixture failures (#239 )
    - [x] Kibana logstash-* index initialization (#187)
    - [ ] Azure deployment
        - [ ] Complete upgrade to latest Azure SDK
        - [ ] Support Ceph (#174)
    - [ ] hive headend services
        - [ ] asset location
        - [ ] client version
        - [ ] client binaries
    - [ ] neon-cli
        - [ ] update check command (#51)
        - [ ] unit tests (#6 )
        - [x] uncomment prepare/setup redaction (#225)
    - [ ] Mac/OSX
        - [ ] features (#127, #3)
        - [ ] virtual box provisioning (#127)
        - [ ] testing (#118, #169)
    - [ ] Client setup
        - [ ] Windows (#1, #2)
        - [ ] OSX (#4)
    - [ ] Minimal cluster dashboard  (#284)
&nbsp;
- [ ] Website, promotional materials and video demos
- [ ] AWS provisoning (#40) - low priority
