### ISSUE TITLE
Cadence: .NET client and GOLANG proxy

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#488]
## Introduction

This issue describes how we're going to implement a .NET cadence-client.  Currently, Cadence has golang and Java clients, but .NET isn't supported due to the lack of a Thrift library for .NET.  There's been some talk by the Cadence folks about adding HTTP and/or gRPC support to Cadence server but actually doing that doesn't seem to be a priority.

The essential idea here is to write a .NET client library that starts a golang app that acts as a proxy to Cadence server and use HTTP to communicate between the .NET library and the golang app.  The .NET library will embed Windows, Linux, and OSX versions of the golang proxy binary as resources and will write it to disk first and then launch it when a .NET application establishes the first connection for an application.  The golang process started will continue to run and handle any new connections.  The .NET client will terminate the golang process when the last connection is closed by the application.

## Terminology

* **cadence-client:** Is the .NET cadence-client we're building
* **cadence-proxy:** The golang program acting as the shim between the cadence-client and the actual Cadence cluster.
* **cadence-proxy message:** or just _proxy message_, are binary messages used for communication between the cadence-client and the cadence-proxy.

## Neon.Cadence Library and Executables

The cadence-proxy is simply a GOLANG executable which will be cross-compiled for the three important target environments: Windows, Linux, and OSX.  **Neon.Cadence** is a .NET Standard 2.0 library that will embed the three Cadence executables as binary resources.  .NET applications will reference the **Neon.Cadence** library and then make calls to establish Cadence Server connections, manage namespaces, define workflows, and then register workflow and activity handlers.

### cadence-proxy lifecycle

The cadence-client manages the lifecyle of the cadence-proxy process in production, something like this:

1. The .NET application instantiates a Neon.cadence-client instance to establish a connection to a Cadence Server.

2. If this is the first Cadence connection, then the cadence-client will write the cadence-proxy resource binary that's appropriate for the current platform to disk (if the executable doesn't already exist) and start it, specifing the network endpoint the cadence-proxy is expected to listen on.  For subsequent client connections, the library will start another cadence-proxy instance using the existing executable file.

3. After the cadence-client starts the proxy, it will send it a **ConnectRequest** message specifying the network endpoint where the library is listening as well as the details for the Cadence cluster being targeted (more details below).  The proxy will sent a **ConnectReply** message back to the library indicating success or failure.

4. As the .NET application performs various operations via the library, the library will submit the appropriate requests to the proxy via HTTP to its networkl endpoint.

5. Eventually the .NET application will close its Cadence server connection.  The cadence-client signals the cadence-proxy to terminate itself by sending it a **TerminateRequest** message.

The lifecyle above describes how this works for production.  The cadence-client will also provide options to connect to an already running cadence-proxy instance for development and debugging purposes.

### cadence-proxy command line

The cadence-client will persist cadence-proxy executable to disk using a file name appropriate for the current platform: **cadence-proxy.exe** for Windows and just **cadence-proxy** for Linux and OSX and then start the proxy via a command like like:
```
cadence-proxy --listen 127.0.0.1:5555 [--log-level level] [--debug]
```
* `--listen` is required and specifies the network endpoint where the cadence-proxy will listen for requests
* `--log-level` is optional specifies the logging level, one of: `panic`, `fatal`, `error`, `warn`, or `debug`.  This should default to `info` when not passed.
* `--debug` is optional and indicates that the cadence-proxy should run in debug mode.

**Note:** The cadence-client will dynamically select an unused ephemeral network ports at runtime by default. 

## cadence-client/proxy communication

The client and proxy will communicate on a local loopback address via HTTP with each side deploying an HTTP server.  cadence-proxy messages can be sent in either direction.  The .NET client and proxy are tightly coupled, so the binary message format and protocol is not designed to support backwards compatibility, since these two components will always be packaged and deployed together.

The low-level Client/proxy communication protocol is **one-way**: the client can send messages to the proxy and the proxy can send messages to the client, but other than the HTTP 200 response (or 400/404/405 for invalid requests).  The server may return an error string in the response content for 400/404/405 responses.  In general though, operation replies are not returned in the PUT response.  The query/reply pattern will be implemented asynchronously at a higher level.

## cadence-client/Proxy Endpoint Paths

The cadence-client and Proxy will both listen for HTTP PUT requests on a specified IP address and port and each of these will initially support two endpoint URI paths:

* **"/":** Is where normal communication between the library and proxy takes place.  Messages PUT to here will be process and if the request is valid, result in the PUT of a reply to the other side.

* **"/echo":** Is a special testing endpoint.  Messages PUT to this endpoint are to be deserialized, copied to a new message of the same type which should be serialized and returned as the PUT response.  This is used for integration to verify that both the library and proxy have implemented serialization correctly.  This endpoint performs no other function.

## Cadence Terminology

* **Workflow:** These orchestrate one or more _activities_ each of which performs an idempotent task.  Workflows are started with zero or more parameters and then schedule a sequence of activities based on the input parameters and the results from already completed activities.

* **Activity:** These perform the actual work for a workflow.  Activities are fundamentally idempotent and Cadence ensures that any given activity is executed only once and that its results are persisted so that the same results will be returned when an already-completed activity is replayed.

* **Signal:** Cadence provides a way to asynchronously send signals to a workflow.  Signals are named by a string and also include a string as the payload.

* **Signal Channel:** Workflows configure themselves to receive signals by creating a signal channel named for the desired signal.

## cadence-proxy Message Format

This formats designed to be a very simple and flexible way of communicating operations and status between the cadence-client and proxy.  The specific  message type is identified via the `Type` property (one of the `MessageType` values.  The `Args` dictionary will be used to pass named values.  Binary attachments may be passed using the  `Attachments` property, a list of binary arrays.

This is serialized to bytes using a simple structure consisting of 32-bit  integers, UTF-8 encoded strings, and raw bytes with all integers encoded using little-endian byte ordering.  Strings are encoded as a 32-bit byte length, followed by that many UTF-8 encoded string bytes.  A ZERO byte length indicates an empty string and a length of -1 indicates a NULL string.  Encoded strings will look like:
```
+------------------+
|      LENGTH      |   32-bit (little endian)
+------------------+
|                  |
|      UTF-8       |
|      BYTES       |
|                  |
+------------------+
```
A full encoded message will look like:
```
+------------------+
|   MESSAGE-TYPE   |   32-bit
+------------------+
|  PROPERTY-COUNT  |   32-bit
+------------------+
|                  |
|  +------------+  |
|  |   NAME     |  |
|  +------------+  |
|  |   VALUE    |  |
|  +------------+  |
|       ...        |
|                  |
+------------------+
|   ATTACH-COUNT   |   32-bit
+------------------+
|                  |
|  +------------+  |
|  |   LENGTH   |  |   32-bit
|  +------------+  |
|  |            |  |
|  |            |  |
|  |   BYTES    |  |
|  |            |  |
|  |            |  |
|  +------------+  |
|       ...        |
|                  |
+------------------+
```
The message starts out with the 32-bit message type followed by the number of properties to follow.  Each property consists of an encoded string for the property name followed by an encoded string for the value.

After the properties will be a 32-bit integer specifying the number of binary attachment with each encoded as its length in bytes followed by that actual attachment bytes.  An attachment with length set to -1 will be considered to be NULL.

Proxy messages will be passed between the cadence-client and proxy via <b>PUT</b> requests using the **application/x-neon-cadence-proxy** content-type.  Note that request HTTP responses in both directions never include any content.

**NOTE:** It is possible that some properties may not be serialized for a message.  This should be intepreted at the low-level as if the property value was serialized as NULL and at higher levels as if the property was set to the default value for the type (e.g. NULL for strings, FALSE for booleans, 0 for integers, etc). 

### Common Property Type Serialization

Both the cadence-proxy and Library will need to agree on how certain common property types will be formatted as strings within message properties.  Here's what we're going to do for various types:

* **boolean:** These will be serialized as either "true" or "false" (lowercase).

* **integer:** These will be serialized as you'd expect with an optional leading "-" for negative numbers.  Note that a leading "+" is not allowed.

* **floating point:** These will be serialized like 1.2345 with an optional leading "+\-" sign.  There must be at least one digit before the decimal point.  Note that the decimal point must be omitted if there are no fractional digits and that the decimal point must be a period (not a comma or anything else used for other cultures).  Invalid numbers will be serialized as "NaN".  Scientific notation is also supported.

* **date/time:** Serialized as: **yyyy-MM-ddTHH:mm:ss.ffffffZ**

* **time span:** We're going to express these as a 64-bit integer number of *ticks*, where a single *tick* equals 100 nanoseconds (the .NET standard).

**json:** For more complex property types, we'll simply serialize them to JSON and persist the JSON text as a property.

### Request and Reply Messages

The cadence-client and cadence-proxy communicate by transmitting request and reply messages.  Either side initiates an operation by sending a request message to its peer and when the peer completes the operation or there's an error, the peer will transmit a reply message back to the original sender.  Note that reply messages are separate HTTP PUT requests.  Reply messages **are not** returned as the HTTP response to a request message.

Request messages transmitted from either side are submitted using the HTTP PUT method.  The receiving side will generally respond with an 200 (OK) status code or 400 (Bad Request) if the proxy message could not be parsed.  A message sender that receives a 200 response will expect the target to respond with a corresponding reply message in the future.  In production, we should never see a 400 response, because that probable means there's a bug in the serialization code on one side or the other.

Reply messages transmitted from either side work the same.  They're transmitted as PUT requests and the sender will expect a 200 or 400 status code as the response.

All request and response messages will include a **RequestId** property the uniquely identifies the specific request.  This will simply be a 64-bit integer encoded.  The cadence-client and cadence-proxy will each maintain a global **nextRequestId** variable that will be incremented (protected by a mutex) every time a new request message is sent.  Each reply message will include the same **RequestId** received with the corresponding  request message.  This will be used by the reqiesting side to correlate received replies with the original request.

Reply messages will also include an optional `Error` property persisted as a JSON string:  This will look lilke:
```
{
  "String": "BadRequestError",
  "Type": "custom"
}
```
where:

* **String** is the Cadence/GOLANG error string
* **Type** is one of  "cancelled", "custom", "generic", "panic", "terminated", or "timeout"

## Message Type hierarchy

This section discusses how proxy messages are organized using common base message classes.

**NOTE:** For the sections below, we're going to specify request and response messages using a minimized C# class syntax with the idea that these will be serialized into the message format described above.  These classes will actually be implemented within the Neon.Cadence library and we should also do the equivalent in GOLANG for within the cadence-proxy.

The cadence-client and the cadence-proxy will communicate using the message types listed here:

[Message Types](https://github.com/nforgeio/neonKUBE/blob/master/Lib/Neon.Cadence/MessageTypes.cs)

### ProxyMessage

The `ProxyMessage` class is inherited by all other message types and provides basic serialization related functionality.  
```
class ProxyMessage
{
    int                         Type;
    Dictionary<string, string>  Properties;
    List<byte[]>                Attachments;
}
```
These properties map closely to the serialized message format described above.

### ProxyRequest

The `ProxyRequest` class is inherited by all request messages.  Its purpose is to add the `RequestId` property that is common across all requests.
```
class ProxyRequest : ProxyMessage
{
    string RequestId;
    TimeSpan Timeout;
}
```

### ProxyReply

The `ProxyReply` class is inherited by all reply messages.  Its purpose is to add the `RequestId` and optional error related properties.
```
class ProxyRequest : ProxyMessage
{
    string RequestId;
    string Error;
}
```
where:

* `Error` is optional JSON describing an error.  This will be set to `null` when there is no error.

**NOTE:** The cadence-client is going to use a non-null `Error` property to map the GOLANG error to a .NET exception type.  For example, `Error`="EntityNotExistsError" will be mapped to the .NET `CadenceEntityNotExistsException`.  `ErrorDetails` (if not `null`) will be set as the .NET exception message.

### Workflow Messages

All Workflow related messages derive from either `ProxyWorkflowRequest` or `ProxyWorkflowReply`.  These classes add the `ContextId` property which is used to identify the workflow context associated with the message.
```
class WorkflowProxyRequest : ProxyRequest
{
    string ContextId;
}

class WorkflowProxyReply : ProxyReply
{
    string ContextId;
}
```

### Activity Messages

All Activity related messages derive from either `ProxyActivityRequest` or `ProxyActivityReply`.  These classes add the `ContextId` property which is used to identify the activity context associated with the message.

**NOTE:** In theory we could have shared a common implementation with the workflow request/reply messages but we're separating these because they might diverge in the future and I don't want to have inheritence nest too deeply.
```
class ActivityProxyRequest : ProxyRequest
{
    string ContextId;
}

class ActivityProxyReply : ProxyReply
{
    string ContextId;
}
```

## Next Steps

Rather than describing the behavior of all of the proxy messages here (this issue is already pretty big), I'm going to author and link to additional issues that will progressively take us through the implementation.

- [x] [#1: Cadence Scenario: Proxy lifecycle](https://github.com/nforgeio/neonKUBE/issues/494)
- [x] [#2: Cadence Scenario: Domain management](https://github.com/nforgeio/neonKUBE/issues/502)
- [x] [#3: Cadence Scenario: Baby workflow](https://github.com/nforgeio/neonKUBE/issues/512)
- [x] [#4: Cadence Scenario: Client API](https://github.com/nforgeio/neonKUBE/issues/513)
- [ ] [#5: Cadence Scenario: Final touches](https://github.com/nforgeio/neonKUBE/issues/530)

**Comment by jefflill** [comment]
Closing this one because we have other issues tracking the remaining work.
