### ISSUE TITLE
Java-aligned Cadence Client

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#580]
We're going to try to align the .NET Cadence client to look more like the Java client.  The current API surface area is a combination of the GOLANG client with a bit of the Java client mixed in.

**First thoughts:**

- [x] Root namespace will be **Neon.Cadence** and we're going to put most user-facing API elements in the root namespace (I don't like having to hunt around for types and needing a bunch of duplicate `using` statements in source files. 

- [x] The main client will be called `CadenceClient`.  This maps loosely to a combination of `IWorkflowService` and `WorkflowClient`.

  It looks like Java integrates the domain client functions here, so we will too.

- [x] Each `CadenceClient` instance will map to and manage a **cadence-proxy** process, like we do now.  We'll need to decouple the workflow operations though (the old scheme was broken anyway)

- [x] .NET is not going to implement that static `Workflow` and `Activity` classes like Java does.  The problem is that the Java client depends on being able to manage threads such that they can save the current workflow or activity state as thread-local data.  The problem with this for .NET is that we're taking advantage of .NET `Task` and `async/await` which is perfectly suited to workflow implementations which by design mainly coordinate other workflows and activities with brief logic computations.  This will be the case as well for many activities that simply do some I/O (network, file, database,...) which will generally be able to be coded as `async` as well (I'm probably also going to support dedicated threads for CPU intensive activities).

  There are a few reasons for not supporting these static classes:

  * Although .NET provides `AsyncLocal<T>` as a way to manage ambient `Task` state, it only works for code executing in a thread associated with the parent task or any of its descendants.  If a task creates a thread, `AsyncLocal<T>` will return NULL when called on the new thread which will probably be unexpected by most developers.  This isn't a huge deal for workflows because folks really shouldn't be starting threads for these anyway, but this will be problematic for activities.

  * Static classes like these are generally considered to be an anti-pattern for .NET apps these days.  Static classes cannot implement interfaces which means they can't easily be mocked for unit tests.

  * This just feels weird to me.  There are very few .NET APIs I can think of that publicly expose static classes like this to expose ambient thread/task state like this to regular developers.  Frameworks like ASP.NET do this sort of thing internally, but there's almost never a need for developers be aware.

  The first cut at the .NET client will define `IWorkflowBase/WorkflowBase`, `IActivityBase/ActivityBase` and will require that user workflow and activity classes inherit or implement these.  The nice thing about this is that a workflow or activity can simply pass itself to library methods to give the library access to all of the workflow/activity properties and methods.  This will work consistently regardless of how the library does threading and just seems cleaner.  To align better with the Java client, we're going to implement the `IWorkflow/Workflow`, and `IActivity/Activity` interfaces and classes.  This map closely to the Java static `Workflow` and `Activity` types but are not static for .NET.  Instead, `IWorkflowBase` defines the `IWorkflow Workflow` property and `IActivityBase` defines the `IActivity Activity` property with the expectation that the workflow and activity implementations will use the properties to obtain state and perform operations.  This will look very much like their Java counterparts.

  This means that the .NET client will instantiate a new instance for each activity, unlike the Java client which uses a shared instance for each activity type.  This will relax the Java requirement that activity implementations be thread-safe and should also seem na tural to migrating Java developers unless they're actively coordinating activities using instance members which seems unlikely.  You can still do this in .NET but you'd need to use `static` members for this (which seems more natural to me anyway).

- [x] Test on .NET Framework.

- [x] We need to collaborate with Uber on being notified of workflow evictions so maintain .NET alignment with the GOLANG client.  I need to do some more thinking about what we'd do with terminated workflows.  `Dispose()` will fail if the task hasn't completed.  The best I can think of right now is for workflow executions to include a cancellation token, which we'll cancel.

  Moved to #656 

- [x] The current **cadence-proxy** is not handling workflow methods that return a future correctly and it's possible for operations that are not immediately awaited to be executed by the **cadence-proxy** out-of-order.  The fix is to not implement these methods using `async`, manually submit the operation to the proxy and then wait for the proxy to send a new `AckReply` message that acknowledges that it has make the corresponding client code before returning from the .NET method.  This will ensure that the networking/task/threading stacks don't end up messing with the execution order.  This will require some **cadence-proxy** changes.

  Moved to #627

  **ANSWER:** I believe the new workflow code that ensures that only a single **cadence-proxy** operation may be in flight at a time for a given workflow will address this.

- [x] Java API doesn't look like it supports optional method parameters.  I believe this is why the Cadence Java API defines all of these *request* classes.  We're going to take advantage of C# optional parameters to avoid defining many/most of these request classes.

- [x] The GOLANG client doesn't appear to support batched operations (and I'm not sure what these are) so .NET won't support these either.

---

**Implementation Tasks:**

- [x] Update the **cadence-proxy** build to temporarily copy the output binaries to the new library.
- [x] Port `CadenceClient` and all of the messages so we can manage the **cadence-proxy** process and verify that we can talk to it.

- [x] Align the `CadenceClient` APIs with `IWorkflowService`:

  - [x] `DeprecateDomain`
  - [x] `DescribeDomain`
  - [x] `DescribeTaskList` - moved to #699
  - [x] `DescribeWorkflowExecution` - moved to #699
  - [x] `GetWorkflowExecutionHistory` - moved to #699
  - [x] `ListClosedWorkflowExecutions` - moved to #700 
  - [x] `ListDomains` - moved to #699
  - [x] `ListOpenWorkflowExecutions` - moved to #700 
  - [x] `QueryWorkflow`
  - [x] `RegisterDomain`
  - [x] `RequestCancelWorkflowExecution`
  - [x] External activity operations:
    - [x] `RecordActivityHeartbeat`
    - [x] `RecordActivityHeartbeatById`
    - [x] `RespondActivityTaskCanceled`
    - [x] `RespondActivityTaskCanceledByID`
    - [x] `RespondActivityTaskCompleted`
    - [x] `RespondActivityTaskCompletedByID`
    - [x] `RespondActivityTaskFailed`
   - [x] `SignalWithStartWorkflowExecution`
   - [x] `SignalWorkflowExecution`
  - [x] `StartWorkflowExecution`
  - [x] `TerminateWorkflowExecution`
  - [x] `UpdateDomain`
&nbsp;
- [x] Implement a worker that executes both activities and workflows.  The cleanest way would be to include individual boolean properties in the message sent to **cadence-proxy**.
- [x] Are we already supporting `DisableStickyExecution` and `StickyScheduleToStartTimeout ` already for new workers?  These seem new to me.
- [x] These methods have new **domain** parameters that need implementing.  We should also verify that we've implemented this for all other methods:
  - [x] `CadenceClient.DescribeWorkflowExecutionAsync()`
  - [x] `CadenceClient.QueryWorkflowAsync()`
  - [x] `CadenceClient.CancelWorkflowExecutionAsync()`
  - [x] `CadenceClient.TerminateWorkflowAsync()`
  - [x] `CadenceClient.SignalWorkflowWithStartAsync()`
&nbsp;
- [x] Replace the old **Neon.Cadence** and **Test.Neon.Cadence** projects with the new implementations.  Also replace `Neon.Xunit.Cadence.CadenceFixture` with `Neon.Xunit.Cadence.CadenceFixture2`.
- [x] Restore the **cadence-proxy** build so that it doesn't make second copies of the binaries.
- [x] Implement logging
- [x] Implement metrics.  Here are some possible libraries for doing this:
  * [metrics.net](https://github.com/Recognos/Metrics.NET/wiki): This one looks pretty good at first look and was ported from a Java project.  It has several adapters including Graphite, ElasticSearch, Prometheus, DataDog, DataDog, and Google Analytics.  It's also possible to build custom adapters.

    Moved to #657
&nbsp;
- [x] Additional Testing:
  - [x] `CadenceClient.DeprecateDomainAsync()`
  - [x] `CadenceClient.DescribeDomainByIdAsync()`
  - [x] `CadenceSettings.DefaultDomain` can be NULL now.

    Tracking these in #700
&nbsp;
- [x] Implement `IDataConverter` and add a property to `CadenceClient` so developers can customize this.  We'll default this to a JSON.NET based implementation.

---

**Differences from the Java Client:**

* The .NET API is `Task` centric and relies on C# `async/await` primitives.  Threads should never be used in workflows but may be used in activities.  Most API methods will be `async` and their names will typically match the corresponding Java API, but with `Async` appended to match .NET conventions.

* The .NET API uses C# properties rather than mirroring the Java `getXXX()/setXXX()` method pattern.

* Durations are typically expressed using .NET `TimeSpan`.  This includes durations that the Java API expresses as seconds.  Under the covers, these will be converted to seconds where necessary and we rely on the Cadence GOLANG client to handle any rounding.

* Time values are exposed using .NET `DateTime`.  We typically name any time properties with `TimeUtc` as the suffix to make it clear that times are relative to UTC.

* Renamed `IServiceClient` to `CadenceClient` and .NET provides the `CadenceSettings` class to specify the target cluster, etc.  `IServiceClient` just seems to generic to me and seems likely to result in name conflicts (I've implemented things named `IServiceClient` in the past).  `CadenceClient` is disposable which follows typical .NET conventions and is also serializable from/to JSON and YAML to make it easy to implement configuration via Kubernetes configs, etc.

  .NET also rolls the Java `WorkfowClient` capabilities into `CadenceClient` so we will not be providing a `WorkflowClient` class.  This works because `CadenceClient` can be constructed with a default Cadence domain and it's also possible to specify other domains as parameters when required.  This should satisfy most use cases.

* The Java client does not require preregistration of workflow and activity types (which is nice).  Unfortunately, the .NET client will require preregistration because the underlying GOLANG client requires explicit registration and it's not possible to register new types after the workers have started.  .NET will mitigate this by providing methods to register workflow and activity types individually or to register all (tagged) workflow and activity types in an assembly.  The latter will be almost as convenient as Java for applications that need to register everything while also allowing finer control over what gets registered.

* The .NET client includes the `Domain` property in `WorkflowOptions` and `ActivityOptions`.

*  The .NET `CadenceClient` includes a `DataConverter` property which can be customized by the end user.  This defaults to an internal JSON based implementation.  We don't currently provide a way to customize the converter for specific workers yet (or for specific workflow stubs, if that's a feature).  We'll add this in the future.  The priority will be stub converter first, worker converter next, and finally the client's converter.

* Class, Interface, Method, Property, Enumeration names have been changed follow C#/.NET naming conventions: PascalCase for public names, CamelCase for internal/private names, *Async* suffix for async methods, etc.

* Strings are nullable in C#/.NET, so the .NET client doesn't need the extra wrapper types that Java/GOLANG has so that NULL can be specified.

* The .NET API uses default parameters where appropriate so that developers won't have to construct separate objects to pass as parameters for most situations, so we're not following the Java client's request/response naming convention for method parameters.  Because of this, it doesn't make a lot of sense to use that naming convention for results either.  Instead of doing this, we're going to just name the result type to be closer to what the result actually is.  So, instead of having `CadenceClient.DescribeDomainAsync()` return a `DescribeDomainResponse`, it will return `DomainDescription` which is much more consistent with .NET conventions.  We're going to do this throughout the code.

- [x] `RetryOptions` specifies the non-retryable errors a bit differently than the Java client.  We can't specify arbitrary .NET exceptions like Java does because the retries are actually being handled by the GOLANG client.  We currently allowing developers to specify GOLANG error strings but it may be possible to more closely align this by allowing the specification of exceptions that derive from `CadenceException`.  We'll take another look when the port is further along.

  Moved to #662 

* **securityToken:** Both the Java and GOLANG clients accept security tokens as parameters to various requests.  I'm not entirely sure where these come from or how they work.  We're going to include this in the `CadenceSettings` associated with the `CadenceClient` and we'll implicitly pass along with the operations that accept such a token and we'll figure out how this works later.

  This assumes that there are no important use cases where an application needs to use different security tokens on a particular client instance.  Applications can workaround this limitation by opening another client with the new token.  If we find that using multiple security tokens on a single client is important, we'll add optional securityToken parameters to methods where they make sense and use the client's token as the default.

* The Java client implements the builder pattern for initializing things like settings and makes setting properties read-only.  .NET is not going to implement this pattern and instead, we're going to have the properties by read/write so things like settings will be persistable as JSON/YAML or can be initialized via the convenient C# object initialization syntax.

* .NET doesn't currently support cross-datacenter replication.  This is an advanced feature that we're going to defer to a future release.

* Some Java methods allow a custom identify to be specified.  .NET will always use the identity specified when creating the client.

* `CadenceClient` can be associated with a default domain specified by `CadenceSettings` (this can be NULL).  The API defines various methods that include `domain` as an optional parameter.  These methods will default to use the client's default domain but will require that domain be passed as a parameter when the default is NULL.  This will be easy to use while also maintaining the Java ability to override the domain.

* Unit Testing: .NET doesn't implement an emulator yet and also doesn't provide ways to override workflow and activity type registrations for testing like Java does.  We're deferring these for a month or two while we get the basics working and have a chance to try this in production.  We'll unit test against a local [nforgeio/cadence-test](https://cloud.docker.com/u/nkubeio/repository/docker/nkubeio/cadence-test) Docker container in the meantime. 

* .NET `Worker` class differs from the Java class due to differences in how the GOLANG API works:
  * Workflow and Activity registrations are implemented on the `CadenceClient` rather than `Worker` to correspond to the GOLANG implementation.

  * The only real operation .NET workers support is `Worker.Dispose()` which can be used to gracefully stop a worker before disposing the associated `CadenceClient`.  Java worker APIs such as `getTaskList()`, `suspendPolling()`, `resumePolling()`, `isSuspended()`, are not implemented on GOLANG and are not supported by .NET either.

- [x] We need to figure out how to create a new workflow that is disconnected from the existing (cancelled) workflow such that the new workflow can clean up things.

  **NOTE:** The Java client doesn't appear to have this functionality.  I suspect they just tell folks to start an external workflow to handle cleanup.

* External activity heartbeats and completion works a bit differently from the Java client.  The completion methods for Java are in a separate activity client class where as .NET includes these in `CadenceClient`.  The method names have also been changed.

* `IWorkflowService/CadenceClient:` We're going to defer implementing these.  I'm assuming that these are lower-level functions that are used to implement the workers and that the worker implementations will probably be good enough for most real-world scenarios:
    * `PollForActivityTask`
    * `PollForDecisionTask`
    * `ResetStickyTaskList`
    * `RespondActivityTaskFailedByID`
    * `RespondDecisionTaskCompleted`
    * `RespondDecisionTaskFailed`
    * `RespondQueryTaskCompleted`
&nbsp;
* `WorkerOptions` is a bit different from Java due differences between the Java API and GOLANG API underlying the .NET client:
  * .NET doesn't include `ActivityPollerOptions` and `WorkflowPollerOptions`.
  * .NET doesn't include `InterceptorFactory`
  * .NET doesn't include these retry options: `ReportActivityCompletionRetryOptions`, `ReportActivityFailureRetryOptions`, `ReportWorkflowCompletionRetryOptions`, `ReportWorkflowCompletionRetryOptions` and `ReportWorkflowFailureRetryOptions`.
&nbsp;
* We only partially implemented metadata maps.

- [x] It looks like the Java API uses its `DataConverter` to serialize memo values.  We should do the same.  Moved to #661

- [x] The Java `Workflow` class implements workflow-safe queues.  I need to investigate how these work and see if we can implement these on .NET via built-in local activities or something.

* .NET supports queuing but the model is not as complete as what the Java client offers.  .NET queues are buffered and will support blocking behaviors when a queue is full.  Note that we also ensure that the underlying GOLANG buffered channel capacity is at least 2 so that queue won't block until the message is received.  We also don't provide a way to peek the next value from the queue without removing it.

  Moved to #658

- [x] Additional workflow/activity method attributes:
  - [x] `MethodRetry` - *activity and child workflow methods*
  - [x] `CronSchedule` - *workflow methods* 
  &nbsp;
  Moved to #659
&nbsp;
- [x] .NET client doesn't currently implement workflow stack trace queries.
  Moved to #660

---

**CADENCE-PROXY: required changes:**

- [x] Added the `string SecurityToken` property to the messages below (these are for the future; **cadence-proxy** should handle serialization, but you'll otherwise ignore these for now):
  - [x] `DomainRegisterRequest`
  - [x] `DomainUpdateRequest`
&nbsp;
- [x] `ActivityCompleteRequest` adds the `Domain`, `WorkflowId`, and `RunId` properties.  You'll ignore these if `TaskToken` is not NULL.  When `TaskToken` is not set, you'll call `CompleteActivityById()`, passing the other properties.

- [x] `ActivityRecordHearthbeatRequest` adds the `Domain`, `WorkflowId`, `RunId`, and `ActivityId` properties.  You'll ignore these if `TaskToken` is not NULL.  When `TaskToken` is not set, you'll call `RecordActivityHeartbeatById()`, passing the other properties.

- [x] Support a worker that supports both activities and workflows.

These messages add the `Domain` property so **cadence-proxy** can create and cache GOLANG workflow clients:

- [x] `ActivityExecuteRequest`
- [x] `ActivityRegisterRequest`
- [x] `WorkflowDescribeExecutionRequest`
- [x] `WorkflowGetResultRequest`
- [x] `WorkflowQueryRequest`
- [x] `WorkflowRegisterRequest`
- [x] `WorkflowSignalRequest`
- [x] `WorkflowSignalWithStartRequest`
- [x] `WorkflowTerminateRequest`

The **cadence-proxy** will need to implement these new messages:

- [x] `DomainDeprecateRequest/DomainDeprecateReply`

**Comment by jefflill** [comment]
The Java-like port is basically complete.  There are a few backlogged items we're tracking separately now but otherwise, we're very close for an initial release.
