### ISSUE TITLE
AWS hosting manager

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#978]
Implement this AWS hosting manager.

**DOCUMENTATION:**

https://aws.amazon.com/sdk-for-net/
https://docs.aws.amazon.com/index.html
https://docs.aws.amazon.com/elasticloadbalancing/?id=docs_gateway
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/introduction.html
https://docs.aws.amazon.com/vpc/latest/userguide/working-with-vpcs.html
https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/ec2-apis-intro.html

https://aws.amazon.com/quickstart/architecture/openshift/
[Red Hat OpenShift Container Platform on the AWS Cloud](https://fwd.aws/dwpPW) - **WOW: OpenShift deployment takes 90min!**

**TASKS:**

- [x] Document IAM/access token process
- [x] Refactor `IHostingManager` calls to be `async` (because the AWS API is now fully async)
- [x] AWS limits the sizes of subnet CIDR blocks to `/16 ... /28`.  We should probably enforce this across all cloud environments so cluster definitions can be reused from cloud to cloud with limited changes.
- [x] Connect
- [x] Verify that region and zone exist
- [x] Create VPC and subnet
- [x] Create public IP
- [x] Create load balancer and network ACLs
     - [x] AWS security groups don't have the concept of **deny** like Azure does.  We may need to remove this from the cluster definition `AddressRules` class or perhaps, we can use [Network ACLs](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html) instead.  Network ACLs are **limited to 20 rules each** by default, so we may need to support port ranges sooner.
- [x] Manage external SSH ACL entries
- [x] Refactor SSH certificate creation.  This needs to be done first because AWS doesn't initialize user passwords
- [x] Verify that instance type is available in region
- [x] Create VMs and disks
- [x] Provision
- [x] Placement groups?

**Comment by jefflill** [comment]
**WOOHOO: DONE!**
